export const PRACTICE_OPTIONS = [
    "Contrattualistica Commerciale",
    "Diritto Societario",
    "Diritto Bancario e Finanziario",
    "Contenzioso e Arbitrato",
    "Diritto Immobiliare",
    "Diritto Tributario",
    "Diritto del Lavoro",
    "Proprietà Intellettuale",
    "Diritto Antitrust e Concorrenza",
    "Tech & Data Protection",
    "Project Finance",
    "Venture Capital",
    "Private Equity",
    "Private Credit",
    "ECM",
    "DCM",
    "Leveraged Finance",
    "Arbitrato Internazionale",
    "Diritto Amministrativo",
    "Diritto della Crisi d'Impresa",
    "Compliance 231",
    "Altro",
] as const;

export type Practice = (typeof PRACTICE_OPTIONS)[number];
